### ISSUE TITLE
Create generic contact structure

### ISSUE THREAD

**Issue by Hamartia666** [Codec-University-Napier/Codec-University-Project#67]
# Create student contact entity
## Description

Since university has students, we need to create a entity model to store data regarding students. This is required in order to associate grading, courses etc. to particular students, as well as store user info, because students are also users.

## Tasks

- [ ] Create new entity table for Students
- [ ] The contact model should include:
- First Name
- Last Name
- ID (Key)
- Email
- Phone
- Address
- Matriculation Number
 
# Definition of done
- [ ] All tasks complete
- [ ] Tested
- [ ] Documentation completed
