### ISSUE TITLE
Create class entity

### ISSUE THREAD

**Issue by drewseffi** [Codec-University-Napier/Codec-University-Project#75]
# Create class entity
## Description
Creating the class entity which will hold information on all the classes running in the university. This will be linked with each student taking the class and each teacher who is teaching the class
## Environment
Dataverse
## Tasks
- [ ] Create new entity table for classes
- [ ] The contact model should include:
- ID (key)
- Name
- Available time slots

# Definition of done
- [ ] All tasks complete
- [ ] Tested
- [ ] Documentation completed
