### ISSUE TITLE
Create module entity

### ISSUE THREAD

**Issue by Hamartia666** [Codec-University-Napier/Codec-University-Project#76]
# Create module entity
## Description
The project requires a way to store data regarding modules.
This will hold information on all the modules running in the university.
This will be linked with each student taking the module and each teacher who is teaching in the module.
## Environment
Dataverse
## Tasks
- [ ] Create new entity table for module
- [ ] The contact model should include:
- ID (key)
- Title
- Description

# Definition of done
- [ ] All tasks complete
- [ ] Tested
- [ ] Documentation completed
