### ISSUE TITLE
Create assignment entity

### ISSUE THREAD

**Issue by Hamartia666** [Codec-University-Napier/Codec-University-Project#77]
# Create assignment entity
## Description
Creating the assignment entity which will hold information on the assignments given to students.
This will be linked with each student who has been given the assignment and the teacher(s) that gave the assignment.
It will contain data about the assignment that the students can view.
## Environment
`Dataverse`
## Tasks
- [ ] Create new entity table for assignment
- [ ] The contact model should include:
- ID
- Type
- Description

# Definition of done
- [ ] All tasks complete
- [ ] Tested
- [ ] Documentation completed
