### ISSUE TITLE
Create course entity

### ISSUE THREAD

**Issue by Hamartia666** [Codec-University-Napier/Codec-University-Project#78]
# Create course entity
## Description

We need to create a data table for courses. This entity will be related to modules it contains, students that are onboarded to them
## Environment
`Dataverse`
## Tasks
- [ ] Create entity table
- [ ] Entity should contain attributes:
- ID (Key)
- Name
- Available Slots
- Description
- Faculty (look up)

# Definition of done
- [ ] All tasks complete
- [ ] Tested
- [ ] Documentation completed
